apiVersion: apps/v1
kind: Deployment
metadata:
  name: talentmanager-backend-deployment
  labels:
    app: talentmanager-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: talentmanager-backend
  template:
    metadata:
      labels:
        app: talentmanager-backend
    spec:
      containers:
      - name: talentmanager-backend
        image: 11700345/talentmanager-backend:latest
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: talentmanager-backend-data
            mountPath: "/var/talentmanager-backend_home"
          - mountPath: /var/run/docker.sock
            name: dockersock
            readOnly: false
      volumes:
        - name: talentmanager-backend-data
          persistentVolumeClaim:
            claimName: talentmanager-backendgluster-claim
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: talentmanager-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30002
  selector:
    app: talentmanager-backend
  externalIPs:
    - 10.128.14.26