server:
  servlet:
    context-path: /talentmanager
spring:
  datasource:
    username: root
    password: test
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talentmanager?serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate.format: true