server:
  servlet:
    context-path: /talentmanager
spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.128.14.2/talentmanager?serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate.format: true